project:
  type: website
  output-dir: docs

# Meta
description-meta: "Yuqi Sun — Human Genetics • Computational Biology • Spatial Multi-omics"
author-meta: "Yuqi Sun"

website:
  title: "Yuqi Sun"
  description: "Human Genetics • Computational Biology • Spatial Multi-omics"
  image: "images/me.png"   

 
  navbar:
    background: light  

    left:   
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: News
            href: posts.qmd#category=news    
          - text: Contact
            href: contact.qmd  

      - text: Research
        menu:
          - text: Projects
            href: projects.qmd
            
      - text: Publications
        href: posts.qmd#category=paper
       
            
      - text: Grants & Awards
        href: projects.qmd#category=grant 
           
      - text: Presentations
        href: posts.qmd#category=presentation 
          

    right: 
      - text: CV
        href: files/CV.pdf
      - icon: github
        href: https://github.com/IKatuo
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Yuqi Sun](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template)"
    right:  
      - icon: github
        href: https://github.com/IKatuo
        target: _blank
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://IKatuo.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://IKatuo.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

